---
label: default
hide_body: false
fields:
- type: blocks
  name: blocks
  label: sections
  template_types:
  - 2-colum-text-then-pic
  - quote
  - banner
  - 2-colum-pic-then-text
  - footer-contact-form
  - banner-1
  - banner-2
- type: text
  name: layout
  label: layout
  hidden: true
  default: default
pages:
- index.html
